src/rc/rc-status: fix 'started' output (-Wformat)
OpenRC/openrc pull request #483
Opened 2021-12-10 05:16 UTC by thesamesam

On 32-bit platforms (e.g. HPPA), GCC warns with:
```
../src/rc/rc-status.c:137:49: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 5 has type ‘time_t’ {aka ‘long int’} [-Wformat=]
  137 |                                                 "%02"PRId64":%02"PRId64":%02"PRId64" (%s)",
      |                                                 ^~~~~
  138 |                                                 diff_hours, diff_mins, diff_secs, start_count);
      |                                                                        ~~~~~~~~~
      |                                                                        |
      |                                                                        time_t {aka long int}
```

We expect the output to be 64-bit but time_t isn't always wide enough, so
let's cast to long long which is guaranteed to be.

Fixes: 25d5de8fd9698fed0fdbbd8949fd4089602b796d
See: https://forums.gentoo.org/viewtopic-t-1146117.html
Signed-off-by: Sam James <sam@gentoo.org>

2021-12-10 15:23 UTC, E5ten commented
Shouldn't this be casting to (int64_t), or changing the format to use %lld as well?

2021-12-11 09:38 UTC, SoapGentoo requested changes
Either `PRId64`/`int64_t` or `lld`/`long long`

2021-12-11 09:38 UTC, SoapGentoo commented on src/rc/rc-status.c
> +						(long long) diff_days, (long long) diff_hours, (long long) diff_mins, (long long) diff_secs,
```suggestion
						(int64_t) diff_days, (int64_t) diff_hours, (int64_t) diff_mins, (int64_t) diff_secs,
```

2021-12-11 09:38 UTC, SoapGentoo commented on src/rc/rc-status.c
> +						(long long) diff_hours, (long long) diff_mins, (long long) diff_secs, start_count);
```suggestion
						(int64_t) diff_hours, (int64_t) diff_mins, (int64_t) diff_secs, start_count);
```

2021-12-13 00:32 UTC, closed without merging