Block running service in chroot.
OpenRC/openrc pull request #527
Opened 2022-05-18 15:45 UTC by sulincix

I implemented chroot check like this
https://github.com/systemd/systemd/blob/main/src/basic/virt.c#L861

openrc-run must block if chrooted.

2022-05-18 15:46 UTC, sulincix commented
https://github.com/systemd/systemd/blob/main/src/systemctl/systemctl.c#L1127

2022-12-08 05:30 UTC, dwfreed commented
There are plenty of valid reasons to run openrc within a chroot, so I'm inclined to reject this.  (openrc doesn't even need to run as root or with any particular capabilities so long as you don't intend to use the privileges afforded by the missing capabilities.)

2023-01-15 21:41 UTC, vapier requested changes
agreed that blanket rejecting chroots is wrong.  i don't think systemd does this either ... seems to me that they default to *not* rejecting it, but you can configure it to do so:
https://github.com/systemd/systemd/blob/v252/src/basic/virt.c#L870

if you want to add an rc.conf setting to let people opt-in to stubbing out chroots, i'm amenable to that.

2023-01-15 21:41 UTC, vapier commented on src/openrc-run/openrc-run.c
> +	if(running_in_chroot()){
bad style -- missing whitespace around the various parts

2023-07-28 12:45 UTC, closed without merging