openrc-shutdown: broadcast: simplify non-blocking logic
OpenRC/openrc pull request #709
Opened 2024-05-23 19:34 UTC by floppym

The sigsetjump/siglongjmp logic originates from sysvinit, and was added before the fork() call was there.

Instead of playing games with signal handlers, just let the kernel kill the process with SIGALARM if write() blocks for some unknown reason.

Bug: https://bugs.gentoo.org/923326

2024-05-24 16:45 UTC, N-R-K requested changes

2024-05-24 16:45 UTC, N-R-K commented on src/openrc-shutdown/broadcast.c
> +				if ((fputs(line, tp) == EOF || fputs(text, tp) == EOF)
There's a race here:

```c
fputs(..);
// alarm fires
fputs(..); // 2nd fputs, alarm is no longer present
```

But TBH I don't think I understand why it's blocking to begin with. Shouldn't O_NDELAY prevent that??

2024-05-24 20:20 UTC, N-R-K approved these changes

2024-05-25 02:18 UTC, thesamesam approved these changes

2024-07-22 21:15 UTC, merged